version: "3.8"

services:
  app:
    build: .
    container_name: worker-api-app
    ports:
      - "8080:8080"
    environment:
      - DSN=postgres://user:password@db:5432/worker_db?sslmode=disable
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: worker-api-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: worker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
